### PR TITLE
Handle basic shell command execution

### PR DESCRIPTION
**Pull request by vesln**
It's not super complete implementation but will do just fine for basic stuff like:

```shell
DOCKER_SERVICE=$(boot2docker ip):11211
```

### CODE REVIEW

**Comment by logicalparadox** [comment]
Loving this idea!

I would note in the README that embedded commands are only compatible with node 0.12+. Also, maybe add iojs to the tests and see if that works as well?

:+1:

**Comment by wilmoore** [comment]
This is excellent. Could use this immediately :+1:

**Comment by wilmoore** [comment]
> I would note in the README that embedded commands are only compatible with node 0.12+.

:+1: 

> Also, maybe add iojs to the tests and see if that works as well?

:+1:

**Comment by logicalparadox** [comment]
Oh, one other thing I should mention is that `boot2docker` is actually being depreciated as a tool developers should use directly. There is now the [docker toolbox](https://www.docker.com/toolbox), which encourages the usage of `docker-machine` that can connect to both local docker vms or remote clusters. Your command should be more along the lines of `$(docker-machine ip dev)`, if you follow their one-line virtualbox deploy. 

I recently switched to using this method and it is fantastic. Something to consider.

**Comment by vesln** [comment]
Thanks for the feedback! For some reason I couldn't setup iojs with Travis CI... `nvm` fails to install it. Any suggestions appreciated

**Pull request merged**
