### PR TITLE
Correct empty line parsing (fixes #4).

### LINKED ISSUE #4: Pairs not being parsed after empty line
`OAUTH` field is not being parsed after empty line in env file. Works without empty line though.

```
SERVER_PORT=4001

OAUTH=public
```

### PR DESCRIPTION
**Pull request by wilmoore**
fixes #4 

- add test that verifies empty line issue.
- update parser to use RegExp vs string split.

### CODE REVIEW

**Comment by logicalparadox** [comment]
:+1:

**Comment by logicalparadox** [comment]
released in `2.0.1`

**Comment by vesln** [comment]
Pretty rad!

**Comment by wilmoore** [comment]
:dancer:

**Pull request merged**
