### PR TITLE
code + tests for not parsing ips as numbers

### PR DESCRIPTION
**Pull request by logicalparadox**

### CODE REVIEW

**Comment by logicalparadox** [comment]
All CI tests pass. Merging and releasing as patch.

**Comment by wilmoore** [comment]
Nice PR. One thing though; Looks like there is an inconsistency with the use of semi-colons and the lack of semi-colons. I'd err on the side of leaving them off everywhere.

**Comment by logicalparadox** [comment]
@wilmoore Good catch. Been using standard lately so getting in the habit of not using them. This lib was conceived pre standard.

**Comment by logicalparadox** [comment]
Released in `2.3.1`.

**Comment by wilmoore** [comment]
> Been using standard lately so getting in the habit of not using them.

Yup, same here. Standard is the way to go.

**Pull request merged**
